import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import style1 from "../styles/Home1.module.css"
// import style2 from "../styles/Home2.module.css"
import Link from "next/link";
import Dummy from "./components/dummy";
export default function Home() {
  // console.log(styles);

  return (
    <div className={styles.container}>
      <style jsx>
        {`
          .mainHead {
            background: blue;
          }
        `}
      </style>
      
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, nextjs-blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <nav className={`${style2.con} ${style1.con}`}></nav> */}
        <Dummy/>
      <nav className={`${styles.mainnav}`}>
        <ul>
          <Link href="/blog">
            <a>
              <li className="mainHead">Home</li>
            </a>
          </Link>
          <Link href="/about">
            <a>
              <li>About</li>
            </a>
          </Link>
          <Link href="/contact">
            <a>
              <li>Contact</li>
            </a>
          </Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <p className={styles.description}>A blog for coder by the coder</p>
        <div className={`${styles.alignCenter}`}>
          <h2>Popular Blogs</h2>
          <div className="blog-item">
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is used to design the logic behind web-pages</p>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
